sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t kamrulsaad/react-docker .

script:
  - docker run kamrulsaad/react-docker /bin/sh -c "npm run test -- --coverage"

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-339712886857"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"