services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    command: npm run start
    develop:
      watch:
        - action: sync
          path: .
          target: /app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run test
    depends_on:
      - web
    develop:
      watch:
        - action: sync
          path: .
          target: /app
